export const STUDIO_SCENARIOS = Object.freeze([
    Object.freeze({
        id: 'double-cross',
        title: 'Double Cross',
        description: 'Tv\u00e5 jagande ormar luras in i spelarens kropp.',
        seed: 74291,
        duration: 18,
        worldHalf: 1200,
        speedMultiplier: 1.12,
        food: { count: 420, radius: 930 },
        playerId: 'player',
        actors: [
            {
                id: 'player',
                name: 'AGARSTAKE',
                color: 'agarstake',
                balance: 8.5,
                start: { x: -300, y: 180, angle: -0.18 },
                path: [
                    { time: 0, x: -300, y: 180 },
                    { time: 2.2, x: -30, y: 120 },
                    { time: 4.4, x: 245, y: -30 },
                    { time: 6.7, x: 90, y: -270 },
                    { time: 9.1, x: -235, y: -155 },
                    { time: 11.7, x: -275, y: 135 },
                    { time: 14.1, x: 5, y: 270 },
                    { time: 16.4, x: 300, y: 60 },
                    { time: 18, x: 160, y: -190 },
                ],
            },
            {
                id: 'hunter-red',
                name: 'Viper',
                color: '#ff4040',
                balance: 4.4,
                start: { x: 170, y: 330, angle: -2.65 },
                chase: { target: 'player', lead: 36 },
            },
            {
                id: 'hunter-blue',
                name: 'Nova',
                color: '#9099ff',
                balance: 5.2,
                start: { x: 410, y: -210, angle: 2.8 },
                chase: { target: 'player', lead: 54 },
            },
            {
                id: 'wanderer',
                name: 'Cobra',
                color: '#80ff80',
                balance: 3.1,
                start: { x: -470, y: -350, angle: 0.5 },
                path: [
                    { time: 0, x: -470, y: -350 },
                    { time: 6, x: -90, y: -440 },
                    { time: 12, x: 350, y: -350 },
                    { time: 18, x: 480, y: 100 },
                ],
            },
        ],
        events: [
            { time: 1.6, action: 'boost', actor: 'hunter-red', duration: 1.4 },
            { time: 4.8, action: 'boost', actor: 'player', duration: 1.1 },
            { time: 7.35, action: 'crashInto', actor: 'hunter-red', target: 'player', segment: 32 },
            { time: 10.8, action: 'boost', actor: 'hunter-blue', duration: 1.2 },
            { time: 13.25, action: 'crashInto', actor: 'hunter-blue', target: 'player', segment: 42 },
            { time: 14.4, action: 'boost', actor: 'player', duration: 1.5 },
        ],
        camera: [
            { time: 0, follow: 'player', zoom: 1.42, offsetX: 35, offsetY: 0 },
            { time: 5.5, follow: 'player', zoom: 1.25, offsetX: 0, offsetY: -20 },
            { time: 7.1, follow: 'player', zoom: 1.65, offsetX: -15, offsetY: 5 },
            { time: 9.2, follow: 'player', zoom: 1.32, offsetX: 10, offsetY: 0 },
            { time: 13, follow: 'player', zoom: 1.72, offsetX: 0, offsetY: 0 },
            { time: 14.2, follow: 'player', zoom: 1.25, offsetX: 15, offsetY: -10 },
            { time: 18, follow: 'player', zoom: 1.38, offsetX: 0, offsetY: 0 },
        ],
    }),
    Object.freeze({
        id: 'reference-coil-trap-rough',
        title: 'Coil Trap',
        description: 'A tight purple coil traps a giant red snake, then a teal challenger.',
        seed: 91357,
        duration: 14.8,
        worldHalf: 1450,
        speedMultiplier: 1.45,
        food: { count: 150, radius: 1100 },
        playerId: 'player',
        actors: [
            {
                id: 'player',
                name: 'AGARSTAKE',
                color: '#e030e0',
                balance: 11.5,
                start: { x: -40, y: 45, angle: 1.35, bend: 0.028 },
                path: [
                    { time: 0, x: -40, y: 45 },
                    { time: 1.3, x: -145, y: 165 },
                    { time: 2.7, x: 45, y: 235 },
                    { time: 4.0, x: 210, y: 80 },
                    { time: 5.2, x: 135, y: -145 },
                    { time: 6.5, x: -100, y: -215 },
                    { time: 7.8, x: -245, y: -35 },
                    { time: 9.0, x: -105, y: 155 },
                    { time: 10.1, x: 105, y: 115 },
                    { time: 11.2, x: 190, y: -75 },
                    { time: 12.2, x: 10, y: -175 },
                    { time: 13.5, x: -165, y: -25 },
                    { time: 14.8, x: 25, y: 150 },
                ],
            },
            {
                id: 'giant-red',
                name: 'Titan',
                color: '#ff4040',
                balance: 42,
                start: { x: 310, y: -90, angle: 1.8, bend: 0.0145 },
                chase: { target: 'player', lead: 20 },
            },
            {
                id: 'teal',
                name: 'Viper',
                color: '#80d0d0',
                balance: 8.2,
                start: { x: -330, y: 410, angle: -0.65, bend: -0.012 },
                path: [
                    { time: 0, x: -330, y: 410 },
                    { time: 4, x: -160, y: 310 },
                    { time: 7, x: 120, y: 260 },
                    { time: 9.5, x: 250, y: 35 },
                    { time: 11.8, x: 65, y: -140 },
                    { time: 14.8, x: -180, y: 80 },
                ],
            },
        ],
        events: [
            { time: 0.8, action: 'boost', actor: 'player', duration: 0.8 },
            { time: 2.0, action: 'boost', actor: 'giant-red', duration: 1.2 },
            { time: 3.55, action: 'crashInto', actor: 'giant-red', target: 'player', segment: 44 },
            { time: 5.1, action: 'boost', actor: 'player', duration: 1.0 },
            { time: 8.4, action: 'boost', actor: 'teal', duration: 1.1 },
            { time: 10.0, action: 'boost', actor: 'player', duration: 0.9 },
            { time: 12.55, action: 'crashInto', actor: 'teal', target: 'player', segment: 52 },
            { time: 13.0, action: 'boost', actor: 'player', duration: 1.1 },
        ],
        camera: [
            { time: 0, follow: 'player', zoom: 0.78, offsetX: 35, offsetY: -25 },
            { time: 3.1, follow: 'player', zoom: 0.9, offsetX: 15, offsetY: 0 },
            { time: 4.2, follow: 'player', zoom: 0.76, offsetX: 0, offsetY: 10 },
            { time: 8.5, follow: 'player', zoom: 0.92, offsetX: -10, offsetY: 0 },
            { time: 12.2, follow: 'player', zoom: 1.08, offsetX: 0, offsetY: 0 },
            { time: 13.2, follow: 'player', zoom: 0.86, offsetX: 0, offsetY: -10 },
            { time: 14.8, follow: 'player', zoom: 0.82, offsetX: 0, offsetY: 0 },
        ],
    }),
    Object.freeze({
        id: 'reference-coil-trap',
        title: 'Reference Coil Trap - desktop crop',
        description: 'A giant red snake closes a ring around a smaller pink player, crashes into the player body, and is eaten with production physics.',
        seed: 91357,
        duration: 10.8,
        worldHalf: 2400,
        speedMultiplier: 1,
        food: { count: 0, radius: 620 },
        deathFoodHue: 58,
        playerId: 'player',
        renderMode: 'spectator',
        ui: { hideMinimap: true, balanceBadgeScale: 0.66 },
        actors: [
            {
                id: 'player',
                name: '',
                color: '#e030e0',
                balance: 10.77,
                start: { x: 0, y: 0, angle: 1.28 },
                initialTrail: [
                    { x: 0, y: 0 },
                    { x: -12, y: -34 },
                    { x: -44, y: -55 },
                    { x: -76, y: -39 },
                    { x: -84, y: -4 },
                    { x: -61, y: 22 },
                    { x: -27, y: 21 },
                    { x: -5, y: -2 },
                    { x: -10, y: -39 },
                    { x: -43, y: -67 },
                    { x: -88, y: -70 },
                    { x: -125, y: -40 },
                    { x: -143, y: 15 },
                    { x: -137, y: 82 },
                    { x: -112, y: 150 },
                    { x: -80, y: 220 },
                    { x: -62, y: 300 },
                ],
                path: [
                    { time: 0, x: 8, y: 24 },
                    { time: 0.8, x: 20, y: 38 },
                    { time: 1.55, x: 24, y: 8 },
                    { time: 2.2, x: 4, y: -22 },
                    { time: 2.85, x: -24, y: -12 },
                    { time: 3.3, x: -35, y: 18 },
                    { time: 8.9, x: 70, y: 150 },
                    { time: 10.8, x: 155, y: 205 },
                ],
                foodChase: {
                    from: 2.75,
                    to: 9.15,
                    deathDropOnly: true,
                    stopBalance: 16.31,
                    boost: false,
                    ordered: true,
                    exit: { x: -15, y: 5 },
                },
            },
            {
                id: 'giant-red',
                name: '',
                color: '#e92f43',
                balance: 24.49,
                visualSegmentCount: 850,
                start: { x: 60, y: -85, angle: 1.12 },
                initialTrail: [
                    { x: 60, y: -85 },
                    { x: 55, y: -126 },
                    { x: 0, y: -141 },
                    { x: -61, y: -132 },
                    { x: -112, y: -98 },
                    { x: -141, y: -43 },
                    { x: -146, y: 22 },
                    { x: -124, y: 84 },
                    { x: -80, y: 131 },
                    { x: -20, y: 151 },
                    { x: 44, y: 145 },
                    { x: 101, y: 116 },
                    { x: 137, y: 66 },
                    { x: 150, y: 7 },
                    { x: 140, y: -54 },
                    { x: 113, y: -94 },
                    { x: 166, y: -132 },
                    { x: 232, y: -151 },
                    { x: 304, y: -141 },
                    { x: 368, y: -105 },
                    { x: 410, y: -46 },
                    { x: 423, y: 25 },
                    { x: 408, y: 100 },
                    { x: 367, y: 169 },
                    { x: 304, y: 220 },
                    { x: 226, y: 246 },
                    { x: 145, y: 245 },
                ],
                path: [
                    { time: 0, x: 72, y: -61 },
                    { time: 0.75, x: 96, y: -20 },
                    { time: 1.45, x: 111, y: 36 },
                    { time: 2.05, x: 95, y: 81 },
                    { time: 2.55, x: 57, y: 110 },
                ],
                bodyTargets: [
                    { from: 2.25, to: 4.2, target: 'player', segmentRatio: 0.63, boost: false },
                ],
            },
            {
                id: 'orange',
                name: '',
                color: '#ff4938',
                balance: 16.25,
                visualSegmentCount: 420,
                start: { x: -196, y: -82, angle: 2.75 },
                initialTrail: [
                    { x: -196, y: -82 },
                    { x: -157, y: -101 },
                    { x: -113, y: -95 },
                    { x: -82, y: -65 },
                    { x: -75, y: -22 },
                    { x: -94, y: 17 },
                    { x: -136, y: 35 },
                    { x: -181, y: 25 },
                    { x: -215, y: -8 },
                    { x: -225, y: -52 },
                    { x: -211, y: -96 },
                    { x: -176, y: -131 },
                    { x: -126, y: -148 },
                    { x: -181, y: -166 },
                    { x: -244, y: -176 },
                ],
                path: [
                    { time: 0, x: -215, y: -96 },
                    { time: 3, x: -270, y: -120 },
                    { time: 10.8, x: -430, y: -20 },
                ],
            },
            {
                id: 'teal',
                name: '',
                color: '#28d4aa',
                balance: 10.02,
                start: { x: 235, y: 205, angle: -1.3 },
                initialTrail: [
                    { x: 235, y: 205 },
                    { x: 244, y: 248 },
                    { x: 232, y: 289 },
                    { x: 196, y: 312 },
                    { x: 152, y: 306 },
                    { x: 123, y: 274 },
                    { x: 123, y: 231 },
                    { x: 151, y: 199 },
                    { x: 193, y: 193 },
                    { x: 227, y: 217 },
                ],
                path: [
                    { time: 0, x: 242, y: 174 },
                    { time: 4.2, x: 225, y: 125 },
                    { time: 7.5, x: 280, y: 75 },
                    { time: 10.8, x: 330, y: 105 },
                ],
            },
        ],
        events: [],
        camera: [
            { time: 0, follow: 'player', zoom: 1.92, offsetX: 0, offsetY: 0 },
            { time: 10.8, follow: 'player', zoom: 1.78, offsetX: 0, offsetY: 0 },
        ],
    }),
]);

export function cloneScenario(scenario) {
    return JSON.parse(JSON.stringify(scenario));
}
